name = "vaw-gl"
uuid = "f322f877-6c1a-421f-91a5-c0bfc4c69729"
repo = "git@github.com:eth-vaw-glaciology/Registry-vaw-gl.git"
description = "VAW-GL package registry"

[packages]
d4a64349-7d63-4304-bc85-347e5f0acb8c = { name = "GlacioTeaching", path = "G/GlacioTeaching" }
f6e1814d-c37d-4673-9f0b-038c7b842264 = { name = "GlacioTools", path = "G/GlacioTools" }
